version: '3.3'
services:
  go-eats-flyway:
    image: flyway/flyway
    volumes:
      - ./sql:/flyway/sql
    environment:
      FLYWAY_URL: ${DB_URL}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_LOCATIONS: ${DB_MIGRATIONS}
      FLYWAY_BASELINE_ON_MIGRATE: true
    network_mode: host
  db:
    image: mysql
    container_name: go-eats-database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306